### PR TITLE
Add test framework

### PR DESCRIPTION
**Pull request by mischkew**
Hey @ihmpavel,

I plan to use your video player in one of my projects. I aim to add custom controls, i.e. speed settings and more advanced settings to the video player. Due to the current code design, the controls are not modular in the sense that a user cannot add new control elements without changing the video player component (which is fine, as it was probably not part of the requirements before). I will work on modularization of the video component in the coming weeks (happy to discuss the design with you if you like).

As a starting point, I wanted to introduce a test framework to ensure I don't break stuff along the way. I integrated these changes on my fork so far. You may benefit from these as well, feel free to approve or reject this PR.

-----

This PR adds a Jest + Enzyme + Typescript setup.

We added an `npm test` command which runs the linter, compiler and finally all unit tests. We might only right the unit test via `npm run jest` or `yarn jest`. We can also run jest in interactive mode via `npm run jest -- --watch`.

A sample test can be found in `lib/__test__`.

We used the opportunity to satisfy the linter (no warnings left).

### CODE REVIEW

**Comment by ihmpavel** [comment]
Hi, 

thanks for your PR. Feel free to send any PRs in the future. 

As you have mentioned, the current code design has some flaws. I was thinking of refactoring the code since the rewriting to hooks.

I have just checked your PR and I am almost ready to merge it, but there are two minor issues.

- `jest.config.js` should be added to `.npmignore`
- Also `yarn tsc` creates JS files in `dist` folder (after that `yarn jest` fails). (We should not upload them to npm. Ignore them in `.npmignore` or do not create them?)

Also, what is your point of view changing `npm run lint && npm run tsc-test && npm run jest` to   `yarn lint && yarn tsc-test && yarn jest`. (I know, that it will limit people, who do not use Yarn, but the project uses Yarn by default (`yarn.lock`). Commad `yarn buid` also calls `yarn copy`)

**Comment by mischkew** [comment]
Cool, I'll keep you posted about my progress and probably will create PRs in the future.

Good points. Didn't check the `build`/  `publish` pipeline.

> jest.config.js should be added to .npmignore

Will do that.

> Also yarn tsc creates JS files in dist folder (after that yarn jest fails). (We should not upload them to npm. Ignore them in .npmignore or do not create them?)

I will investigate that.

> Also, what is your point of view changing npm run lint && npm run tsc-test && npm run jest to yarn lint && yarn tsc-test && yarn jest. (I know, that it will limit people, who do not use Yarn, but the project uses Yarn by default (yarn.lock). Commad yarn buid also calls yarn copy)

That's fine I believe. As you said, that's the dev setup, and independent of users integrating the library into their projects. I happily change the flow to yarn-only.

**Comment by mischkew** [comment]
@ihmpavel please see my changes.

* I ignored the jest.config.js in .npmignore
* I only ran jest tests on the lib folder (dist is ignored, thus yarn test doesn't fail anymore)
* I changed the test pipeline to use yarn only
* I configured typescript to not emit any __tests__ files

**Comment by ihmpavel** [comment]
Great job 👏

I don't think, bumping version is required right now.

**Pull request merged**
